apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencost
  namespace: opencost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencost
  template:
    metadata:
      labels:
        app: opencost
    spec:
      containers:
      - name: opencost
        image: ghcr.io/opencost/opencost:1.111.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9003
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: PROMETHEUS_SERVER_ENDPOINT
          value: "http://prometheus-server.prometheus-system.svc.cluster.local:80"
        - name: CLOUD_PROVIDER
          value: "GCP"
        - name: GCP_PROJECT_ID
          value: "neural-diwan-435305"
        - name: CLUSTER_ID
          value: "astro-blog-cluster"
        - name: KUBECOST_NAMESPACE
          value: "opencost"
      - name: opencost-ui
        image: ghcr.io/opencost/opencost-ui:1.111.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi