apiVersion: v1
kind: Service
metadata:
  name: astro-blog-service
  annotations:
    networking.gke.io/load-balancer-type: "External"
spec:
  type: LoadBalancer
  loadBalancerIP: 34.31.187.182  # reserved static IP
  ports:
  - port: 80
    targetPort: 3000
    name: http
  - port: 8080
    targetPort: 8080
    name: metrics
  selector:
    app: astro-blog